"""
Django settings for be_django_rest_api project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from django_variables.api_variables import *

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TEMPLATE_DIRS = (
    os.path.join(BASE_DIR, 'api_manage_users', 'templates'),
    os.path.join(BASE_DIR, 'api_manage_projects', 'templates'),)

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'be_django_rest_api.settings')

if(DJANGO_SETTINGS_MODULE == 'production'):
    # DEBUG = False
    DEBUG = False
    MEDIA_ROOT = '/data/backend/media/'
    ALLOWED_HOSTS = ['api.scorelisto.com']
    SECRET_KEY = DJANGO_SECRET_KEY
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'scorelistodb',
            'USER': 'ndejax',
            'PASSWORD': DJANGO_PSQL_DB_PW,
            'HOST': 'localhost',
            'PORT': '',
        }
    }
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_PRELOAD = True
    X_FRAME_OPTIONS = 'DENY'
    FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o774
elif(DJANGO_SETTINGS_MODULE == 'local'):
    DEBUG = True
    MEDIA_ROOT = '/home/ndejax/work/scorelisto/media/'
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
    SECRET_KEY = '5g73jq4kexfjx4hzt%64t(+iu-rts0)qmxi-@@!e1wh^2-$^bk'
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'scorelistodb',
            'USER': 'ndejax',
            'PASSWORD': '?681Pap!i?',
            'HOST': 'localhost',
            'PORT': '',
        }
    }


WSGI_APPLICATION = 'be_django_rest_api.wsgi.application'

# EMAIL settings
EMAIL_HOST = 'pro1.mail.ovh.net'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'support@scorelisto.com'
EMAIL_HOST_PASSWORD = DJANGO_SUPPORT_EMAIL_PW
EMAIL_USE_TLS = True


# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/


CORS_ORIGIN_ALLOW_ALL = False
# CORS_ORIGIN_WHITELIST doesn't work with tuple...
# CORS_ORIGIN_WHITELIST = 'https://www.scorelisto.com'
CORS_ORIGIN_WHITELIST = 'http://localhost:4200'
CORS_ALLOW_HEADERS = ('content-type', 'enctype', 'authorization', )


DELETE_ACCOUNT_DATA_HOURS = 48

PASSWORD_RESET_TIMEOUT_DAYS = 1

# Application definition

# api_manage_users must be before the other api(s) !
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api_manage_users',
    'api_manage_parameters',
    'api_manage_projects',
    'oauth2_provider',
    'corsheaders',
    'rest_framework',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'be_django_rest_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# 'rest_framework.authentication.TokenAuthentication',
# 'STRICT_JSON': False,
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}


OAUTH2_PROVIDER = {
    # this is the list of available scopes
    'SCOPES': {'read': 'Read scope', 'write': 'Write scope', 'groups': 'Access to your groups'},
    'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuthLibCore',
}

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

# 2 channels * 5 minutes * 60 secondes * 44100 * 4 octets (32 bits)
DATA_UPLOAD_MAX_MEMORY_SIZE = 105840000

MAX_PARAMETER_NUMBER = 100
MAX_PROJECT_NUMBER = 100
MAX_PROCESS_NUMBER = 1

# Free Users
# FREE_MAX_MEMORY_USED = 105840000
# FREE_MAX_LENGTH_TRACK = 60
# FREE_MAX_PROJECT_PER_DAY = 1

FREE_MAX_MEMORY_USED = 1073741842
FREE_MAX_LENGTH_TRACK = 605
FREE_MAX_PROJECT_PER_DAY = 100

# Premium Users
PREMIUM_MAX_MEMORY_USED = 1073741842
PREMIUM_MAX_LENGTH_TRACK = 605
PREMIUM_MAX_PROJECT_PER_DAY = 100
